### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [Aegisub/Aegisub#93]
After boostorg/gil@32fec9f05ba8 build fails. See [error log](https://ptpb.pw/wG5F).

```c++
src/subtitles_provider_libass.cpp:49:10: fatal error: 'boost/gil/gil_all.hpp' file not found
#include <boost/gil/gil_all.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
src/video_frame.cpp:19:10: fatal error: 'boost/gil/gil_all.hpp' file not found
#include <boost/gil/gil_all.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
src/colour_button.cpp:21:10: fatal error: 'boost/gil/gil_all.hpp' file not found
#include <boost/gil/gil_all.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
src/video_provider_dummy.cpp:48:10: fatal error: 'boost/gil/gil_all.hpp' file not found
#include <boost/gil/gil_all.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by plater** [comment]
The attached patch solves this issue
[aegisub-boost169.patch.txt](https://github.com/Aegisub/Aegisub/files/3022789/aegisub-boost169.patch.txt)

**Comment by FichteFoll** [comment]
Also fixed in the following fork:

https://github.com/TypesettingTools/Aegisub/commit/75fc5f38d79ac2a776f6ccc452a8b7b3cd85c397
